// playground-angular/src/app.component.ts
import type { OnDestroy, OnInit } from '@angular/core'
import { CommonModule } from '@angular/common'
import { ChangeDetectionStrategy, Component, computed, signal } from '@angular/core'
import { MarkstreamAngularComponent } from 'markstream-angular'
import { streamContent } from '../../playground/src/const/markdown'
import { LineNumberHandoffCheckComponent } from './line-number-handoff-check.component'
import { TestPageComponent } from './test-page.component'
import { TestSandboxComponent } from './test-sandbox.component'
import { ThinkingNodeComponent } from './thinking-node.component'

const markdownSource = typeof streamContent === 'string' ? streamContent : String(streamContent || '')
const THINKING_TAGS = ['thinking'] as const

function normalizePath(pathname: string | null | undefined) {
  const normalized = (pathname || '/').replace(/\/+$/, '')
  return normalized || '/'
}

function clampDelay(value: number) {
  if (!Number.isFinite(value))
    return 16
  return Math.min(200, Math.max(4, Math.round(value)))
}

function clampChunk(value: number) {
  if (!Number.isFinite(value))
    return 1
  return Math.min(16, Math.max(1, Math.floor(value)))
}

function readNumericInput(event: Event, fallback: number) {
  const value = Number((event.target as HTMLInputElement | null)?.value ?? fallback)
  return Number.isFinite(value) ? value : fallback
}

@Component({
  selector: 'playground-angular-root',
  standalone: true,
  imports: [CommonModule, MarkstreamAngularComponent, LineNumberHandoffCheckComponent, TestPageComponent, TestSandboxComponent],
  template: `
    <app-angular-test-sandbox *ngIf="isSandboxPage(); else nonSandbox" />

    <ng-template #nonSandbox>
      <app-line-number-handoff-check *ngIf="isLineNumberHandoffCheck(); else nonHandoff" />

      <ng-template #nonHandoff>
        <app-angular-test-page
          *ngIf="isTestPage(); else home"
          (navigateHome)="goHome()"
        />

        <ng-template #home>
          <div class="page">
          <header class="header">
            <div class="header-main">
              <div class="title">markstream-angular playground</div>
              <button type="button" class="btn" (click)="goToTest()">
                Open /test
              </button>
            </div>
            <div class="sub">
              Angular playground with streaming demo, standalone /test regression lab, and isolated /test-sandbox.
            </div>
          </header>

          <div class="layout">
            <section class="panel controls">
              <h2>Stream controls</h2>

              <div class="field">
                <label for="delay">Delay (ms)</label>
                <input
                  id="delay"
                  type="number"
                  min="4"
                  max="200"
                  [value]="delay()"
                  (input)="updateDelay($event)"
                >
              </div>

              <div class="field">
                <label for="chunk">Chunk size</label>
                <input
                  id="chunk"
                  type="number"
                  min="1"
                  max="16"
                  [value]="chunkSize()"
                  (input)="updateChunkSize($event)"
                >
              </div>

              <div class="actions">
                <button type="button" class="btn" (click)="toggleStream()">
                  {{ running() ? 'Pause' : 'Resume' }}
                </button>
                <button type="button" class="btn" (click)="resetStream()">
                  Reset
                </button>
                <button type="button" class="btn ghost" (click)="fillAll()">
                  Render all
                </button>
              </div>

              <div class="status">
                <div class="progress">
                  <div class="bar" [style.width.%]="progress()"></div>
                </div>
                <div class="meta">
                  {{ content().length }} / {{ totalLength }} ({{ progress() }}%)
                </div>
              </div>

              <p class="note">
                首页保留主 demo；更完整的跨框架回归入口在 <code>/test</code>，隔离版本对照在 <code>/test-sandbox</code>。
              </p>
            </section>

            <section class="panel preview">
              <markstream-angular
                [content]="content()"
                [final]="isDone()"
                [renderCodeBlocksAsPre]="false"
                [codeBlockStream]="true"
                [customHtmlTags]="thinkingTags"
                [customComponents]="customComponents"
              />
            </section>
          </div>
        </div>
        </ng-template>
      </ng-template>
    </ng-template>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent implements OnInit, OnDestroy {
  readonly thinkingTags = THINKING_TAGS
  readonly customComponents = {
    thinking: ThinkingNodeComponent,
  }

  readonly totalLength = markdownSource.length
  readonly currentPath = signal(typeof window === 'undefined' ? '/' : normalizePath(window.location.pathname))
  readonly content = signal('')
  readonly delay = signal(16)
  readonly chunkSize = signal(2)
  readonly running = signal(true)
  readonly normalizedChunkSize = computed(() => clampChunk(this.chunkSize()))
  readonly progress = computed(() => {
    if (!this.totalLength)
      return 0
    return Math.min(100, Math.round((this.content().length / this.totalLength) * 100))
  })

  readonly isDone = computed(() => this.content().length >= this.totalLength)
  readonly isTestPage = computed(() => this.currentPath() === '/test')
  readonly isSandboxPage = computed(() => this.currentPath() === '/test-sandbox')
  readonly isLineNumberHandoffCheck = computed(() => this.currentPath() === '/line-number-handoff-check')
  readonly isStandalonePage = computed(() => this.isTestPage() || this.isSandboxPage() || this.isLineNumberHandoffCheck())

  private timer: number | null = null

  ngOnInit() {
    if (typeof window !== 'undefined')
      window.addEventListener('popstate', this.handlePopState)
    if (!this.isStandalonePage())
      this.startStream()
  }

  ngOnDestroy() {
    if (typeof window !== 'undefined')
      window.removeEventListener('popstate', this.handlePopState)
    this.stopStream()
  }

  updateDelay(event: Event) {
    this.delay.set(clampDelay(readNumericInput(event, this.delay())))
    if (this.running() && !this.isStandalonePage())
      this.restartStream()
  }

  updateChunkSize(event: Event) {
    this.chunkSize.set(clampChunk(readNumericInput(event, this.chunkSize())))
  }

  goToTest() {
    this.navigate('/test')
  }

  goHome() {
    this.navigate('/')
  }

  toggleStream() {
    if (this.running())
      this.stopStream()
    else
      this.startStream()
  }

  resetStream() {
    this.content.set('')
    this.startStream()
  }

  fillAll() {
    this.content.set(markdownSource)
    this.stopStream()
  }

  private readonly handlePopState = () => {
    this.syncPath()
    if (this.isStandalonePage())
      this.stopStream()
    else if (!this.content())
      this.startStream()
  }

  private syncPath() {
    if (typeof window === 'undefined')
      return
    this.currentPath.set(normalizePath(window.location.pathname))
  }

  private navigate(pathname: string) {
    const nextPath = normalizePath(pathname)
    if (typeof window !== 'undefined' && nextPath !== normalizePath(window.location.pathname))
      window.history.pushState({}, '', nextPath)

    this.currentPath.set(nextPath)

    if (this.isStandalonePage())
      this.stopStream()
    else if (!this.content() || this.content().length >= markdownSource.length)
      this.resetStream()
  }

  private tick() {
    if (this.isDone()) {
      this.stopStream()
      return
    }

    this.content.update((current) => {
      const nextChunk = markdownSource.slice(current.length, current.length + this.normalizedChunkSize())
      return current + nextChunk
    })
  }

  private startStream() {
    this.stopStream()
    if (typeof window === 'undefined')
      return
    this.running.set(true)
    this.timer = window.setInterval(() => this.tick(), this.delay())
  }

  private stopStream() {
    if (this.timer != null && typeof window !== 'undefined') {
      window.clearInterval(this.timer)
      this.timer = null
    }
    this.running.set(false)
  }

  private restartStream() {
    if (!this.running())
      return
    this.startStream()
  }
}

// playground-vue2/src/App.vue
<script>
import MarkdownRender, { setCustomComponents } from 'markstream-vue2'
import { streamContent } from '../../playground/src/const/markdown'
import LineNumberHandoffCheck from './components/LineNumberHandoffCheck.vue'
import TestLab from './components/TestLab.vue'
import ThinkingNode from './components/ThinkingNode.vue'

const markdownSource = typeof streamContent === 'string' ? streamContent : String(streamContent || '')
setCustomComponents('vue2-demo', { thinking: ThinkingNode })

export default {
  name: 'Vue2Playground',
  components: {
    LineNumberHandoffCheck,
    MarkdownRender,
    TestLab,
  },
  data() {
    return {
      content: '',
      delay: 16,
      chunkSize: 2,
      timer: null,
      running: true,
      currentPath: typeof window !== 'undefined' ? window.location.pathname : '/',
    }
  },
  computed: {
    isTestPage() {
      return this.normalizePath(this.currentPath) === '/test'
    },
    isLineNumberHandoffCheck() {
      return this.normalizePath(this.currentPath) === '/line-number-handoff-check'
    },
    isStandaloneCheckPage() {
      return this.isTestPage || this.isLineNumberHandoffCheck
    },
    totalLength() {
      return markdownSource.length
    },
    progress() {
      if (!this.totalLength)
        return 0
      return Math.min(100, Math.round((this.content.length / this.totalLength) * 100))
    },
    normalizedChunkSize() {
      const n = Math.floor(Number(this.chunkSize) || 1)
      return Math.max(1, n)
    },
    isDone() {
      return this.content.length >= this.totalLength
    },
  },
  watch: {
    delay() {
      if (this.running && !this.isStandaloneCheckPage)
        this.restartStream()
    },
  },
  mounted() {
    this.syncPath()
    window.addEventListener('popstate', this.handlePopState)
    if (!this.isStandaloneCheckPage)
      this.startStream()
  },
  beforeUnmount() {
    window.removeEventListener('popstate', this.handlePopState)
    this.stopStream()
  },
  methods: {
    normalizePath(path) {
      if (!path)
        return '/'
      const normalized = path.replace(/\/+$/, '')
      return normalized || '/'
    },
    syncPath() {
      if (typeof window === 'undefined')
        return
      this.currentPath = this.normalizePath(window.location.pathname)
    },
    handlePopState() {
      this.syncPath()
      if (this.isStandaloneCheckPage)
        this.stopStream()
      else if (!this.content.length)
        this.startStream()
    },
    navigate(path) {
      const nextPath = this.normalizePath(path)
      if (typeof window === 'undefined') {
        this.currentPath = nextPath
        return
      }
      if (nextPath !== this.normalizePath(window.location.pathname))
        window.history.pushState({}, '', nextPath)
      this.currentPath = nextPath
      if (this.isStandaloneCheckPage)
        this.stopStream()
      else if (!this.content.length)
        this.startStream()
    },
    goToTest() {
      this.navigate('/test')
    },
    goHome() {
      this.navigate('/')
    },
    tick() {
      if (this.isDone) {
        this.stopStream()
        return
      }
      const start = this.content.length
      const nextChunk = markdownSource.slice(start, start + this.normalizedChunkSize)
      this.content += nextChunk
    },
    startStream() {
      this.stopStream()
      this.running = true
      this.timer = window.setInterval(() => this.tick(), this.delay)
    },
    stopStream() {
      if (this.timer != null) {
        window.clearInterval(this.timer)
        this.timer = null
      }
      this.running = false
    },
    toggleStream() {
      if (this.running)
        this.stopStream()
      else this.startStream()
    },
    restartStream() {
      if (!this.running)
        return
      this.startStream()
    },
    resetStream() {
      this.content = ''
      this.startStream()
    },
    fillAll() {
      this.content = markdownSource
      this.stopStream()
    },
  },
}
</script>

<template>
  <TestLab v-if="isTestPage" @navigate-home="goHome" />
  <LineNumberHandoffCheck v-else-if="isLineNumberHandoffCheck" />

  <div v-else class="page">
    <header class="header">
      <div class="header-main">
        <div class="title">
          markstream-vue2 playground
        </div>
        <button type="button" class="btn" @click="goToTest">
          Open /test
        </button>
      </div>
      <div class="sub">
        Vue 2.6 demo: streaming markdown into the renderer
      </div>
    </header>

    <div class="layout">
      <section class="panel controls">
        <h2>Stream controls</h2>
        <div class="field">
          <label for="delay">Delay (ms)</label>
          <input id="delay" v-model.number="delay" type="number" min="4" max="200">
        </div>
        <div class="field">
          <label for="chunk">Chunk size</label>
          <input id="chunk" v-model.number="chunkSize" type="number" min="1" max="16">
        </div>
        <div class="actions">
          <button type="button" class="btn" @click="toggleStream">
            {{ running ? 'Pause' : 'Resume' }}
          </button>
          <button type="button" class="btn" @click="resetStream">
            Reset
          </button>
          <button type="button" class="btn ghost" @click="fillAll">
            Render all
          </button>
        </div>
        <div class="status">
          <div class="progress">
            <div class="bar" :style="{ width: `${progress}%` }" />
          </div>
          <div class="meta">
            {{ content.length }} / {{ totalLength }} ({{ progress }}%)
          </div>
        </div>
        <p class="note">
          This demo focuses on baseline Vue 2 rendering. Mermaid and KaTeX are
          optional peer dependencies and render when installed.
        </p>
      </section>

      <section class="panel preview">
        <MarkdownRender
          :content="content"
          :final="isDone"
          :typewriter="false"
          custom-id="vue2-demo"
          :custom-html-tags="['thinking']"
        />
      </section>
    </div>
  </div>
</template>
