// packages/markstream-svelte/src/components/PreCodeNode.svelte
<script lang="ts">
  import type { SvelteRenderableNode } from './shared/node-helpers'
  import { encodeDataPayload, getString, sanitizeClassToken } from './shared/node-helpers'

  type Props = {
    node: SvelteRenderableNode
    showLineNumbers?: boolean
  };
  let {
    node,
    showLineNumbers = true,
  }: Props = $props()

  let languageRaw = $derived(getString((node as any)?.language).trim())
  let language = $derived(sanitizeClassToken(languageRaw))
  let code = $derived(getString((node as any)?.code))
  let diff = $derived(Boolean((node as any)?.diff))
  let loading = $derived((node as any)?.loading === true)
  let displayCode = $derived(loading ? code : code.replace(/\r\n$|\n$|\r$/, ''))

  // Non-diff line numbers, aligned with the Vue 3 PreCodeNode.
  let showLineGutter = $derived(showLineNumbers === true && !diff)
  let lineCount = $derived(countCodeLines(displayCode))
  let lineNumbersText = $derived(buildLineNumbersText(lineCount))
  let lineNumberLayoutStyle = $derived(
    showLineGutter
      ? `--markstream-pre-line-number-width: ${Math.max(4, String(lineCount).length)}ch; --markstream-pre-diff-line-number-width: ${Math.max(4, String(lineCount).length)}ch; --markstream-code-padding-left: calc(var(--markstream-pre-line-number-padding-left, 2ch) + var(--markstream-pre-line-number-width, 2ch) + var(--markstream-pre-line-number-padding-right, 1ch) + var(--markstream-pre-line-number-separator-width, 2px) + var(--markstream-pre-line-number-gap-to-code, 1ch));`
      : undefined,
  )

  function countCodeLines(codeStr: string) {
    let count = 1
    for (let index = 0; index < codeStr.length; index++) {
      if (codeStr[index] === '\n') {
        count++
      }
      else if (codeStr[index] === '\r') {
        count++
        if (codeStr[index + 1] === '\n')
          index++
      }
    }
    return codeStr.length ? count : 1
  }

  function buildLineNumbersText(count: number) {
    let out = ''
    for (let line = 1; line <= count; line++)
      out += `${out ? '\n' : ''}${line}`
    return out
  }
</script>

{#if !(loading && !code.trim())}
  <pre
    data-markstream-code-block="1"
    data-markstream-language={languageRaw || undefined}
    data-markstream-loading={loading ? '1' : undefined}
    data-markstream-diff={diff ? '1' : undefined}
    data-markstream-original={diff ? encodeDataPayload(getString((node as any)?.originalCode)) : undefined}
    data-markstream-updated={diff ? encodeDataPayload(getString((node as any)?.updatedCode)) : undefined}
    data-markstream-pre="1"
    data-markstream-line-numbers={showLineGutter ? '1' : undefined}
    aria-busy={loading ? 'true' : undefined}
    class:markstream-pre--line-numbers={showLineGutter}
    class={language ? `language-${language}` : undefined}
    style={lineNumberLayoutStyle}
  >{#if showLineGutter}<span class="markstream-pre__line-numbers" aria-hidden="true"><span class="markstream-pre__line-numbers-text">{lineNumbersText}</span></span>{/if}<code class="markstream-pre__code" translate="no">{displayCode}</code></pre>
{/if}

// packages/markstream-angular/src/components/PreCodeNode/PreCodeNode.component.ts
import type { AngularRenderableNode } from '../shared/node-helpers'
import { ChangeDetectionStrategy, Component, Input } from '@angular/core'
import { getString, normalizeCodeLanguage } from '../shared/node-helpers'

function countCodeLines(code: string) {
  let count = 1
  for (let index = 0; index < code.length; index++) {
    if (code[index] === '\n') {
      count++
    }
    else if (code[index] === '\r') {
      count++
      if (code[index + 1] === '\n')
        index++
    }
  }
  return count
}

function getDisplayCode(code: unknown, loading?: boolean) {
  const value = getString(code)
  return loading ? value : value.replace(/\r\n$|\n$|\r$/, '')
}

@Component({
  selector: 'markstream-angular-pre-code-node',
  standalone: true,
  template: `<pre
    [ngClass]="preClasses"
    [ngStyle]="lineNumberLayoutStyle"
    [attr.aria-busy]="loading"
    [attr.aria-label]="ariaLabel"
    [attr.data-language]="language"
    [attr.data-markstream-line-numbers]="showLineNumbers ? '1' : null"
    data-markstream-pre="1"
    tabindex="0"
  ><ng-container *ngIf="showLineNumbers"><span class="markstream-pre__line-numbers" aria-hidden="true"><span class="markstream-pre__line-numbers-text">{{ lineNumbersText }}</span></span></ng-container><code translate="no" class="markstream-pre__code" [textContent]="code"></code></pre>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PreCodeNodeComponent {
  @Input({ required: true }) node!: AngularRenderableNode
  @Input() showLineNumbers = false

  // ─── Line-count caching (mirrors the vue3 PreCodeNode) ─────────────────────
  private cachedCode = ''
  private cachedCount = 1
  private textCount = 0
  private textCache = ''

  get language() {
    return normalizeCodeLanguage((this.node as any)?.language)
  }

  get languageClass() {
    return `language-${this.language}`
  }

  get preClasses() {
    return {
      [this.languageClass]: true,
      'markstream-pre--line-numbers': this.showLineNumbers === true,
    }
  }

  get ariaLabel() {
    return this.language ? `Code block: ${this.language}` : 'Code block'
  }

  get code() {
    return getString((this.node as any)?.code)
  }

  get loading() {
    return (this.node as any)?.loading === true
  }

  get displayCode() {
    return getDisplayCode((this.node as any)?.code, this.loading)
  }

  get codeLineCount() {
    const code = this.displayCode
    if (code === this.cachedCode)
      return this.cachedCount
    this.cachedCount = countCodeLines(code)
    this.cachedCode = code
    return this.cachedCount
  }

  get lineNumbersText() {
    const count = this.codeLineCount
    if (count < this.textCount) {
      this.textCount = 0
      this.textCache = ''
    }
    for (let line = this.textCount + 1; line <= count; line++)
      this.textCache += `${this.textCache ? '\n' : ''}${line}`
    this.textCount = count
    return this.textCache
  }

  get lineNumberLayoutStyle(): Record<string, string> | null {
    if (this.showLineNumbers !== true)
      return null

    const maximumLineNumber = this.codeLineCount
    const width = `${Math.max(4, String(maximumLineNumber).length)}ch`
    return {
      '--markstream-pre-line-number-width': width,
      '--markstream-pre-diff-line-number-width': width,
      '--markstream-code-padding-left': 'calc(var(--markstream-pre-line-number-padding-left, 2ch) + var(--markstream-pre-line-number-width, 2ch) + var(--markstream-pre-line-number-padding-right, 1ch) + var(--markstream-pre-line-number-separator-width, 2px) + var(--markstream-pre-line-number-gap-to-code, 1ch))',
    }
  }
}
