// playground-vue2-cli/src/App.vue
<script>
/* global __MARKSTREAM_VUE2_CLI_DEMO_MD__ */

import MarkdownRender, { setCustomComponents } from 'markstream-vue2'
import LineNumberHandoffCheck from './components/LineNumberHandoffCheck.vue'
import ThinkingNode from './components/ThinkingNode.vue'

const markdownSource = typeof __MARKSTREAM_VUE2_CLI_DEMO_MD__ === 'string'
  ? __MARKSTREAM_VUE2_CLI_DEMO_MD__
  : String(__MARKSTREAM_VUE2_CLI_DEMO_MD__ || '')
const customHtmlTags = Object.freeze(['thinking'])
const codeBlockProps = Object.freeze({ isDark: true })
const probeMode = typeof window !== 'undefined'
  && typeof window.location !== 'undefined'
  && /(?:^|[?&])probe=1(?:&|$)/.test(window.location.search)

setCustomComponents('vue2-demo', { thinking: ThinkingNode })

export default {
  name: 'Vue2CliPlayground',
  components: {
    LineNumberHandoffCheck,
    MarkdownRender,
  },
  data() {
    return {
      content: '',
      delay: 24,
      chunkSize: 2,
      timer: null,
      running: true,
      customHtmlTags,
      codeBlockProps,
      currentPath: typeof window !== 'undefined' ? window.location.pathname : '/',
    }
  },
  computed: {
    isLineNumberHandoffCheck() {
      return this.currentPath.replace(/\/+$/, '') === '/line-number-handoff-check'
    },
    totalLength() {
      return markdownSource.length
    },
    progress() {
      if (!this.totalLength)
        return 0
      return Math.min(100, Math.round((this.content.length / this.totalLength) * 100))
    },
    normalizedChunkSize() {
      const n = Math.floor(Number(this.chunkSize) || 1)
      return Math.max(1, n)
    },
    isDone() {
      return this.content.length >= this.totalLength
    },
  },
  watch: {
    delay() {
      if (this.running)
        this.restartStream()
    },
  },
  mounted() {
    if (!probeMode && !this.isLineNumberHandoffCheck)
      this.startStream()
  },
  beforeUnmount() {
    this.stopStream()
  },
  methods: {
    scheduleNextTick(previousElapsed = 0) {
      if (!this.running || this.isDone)
        return

      if (this.timer != null)
        window.clearTimeout(this.timer)

      const wait = Math.max(
        0,
        Math.max(Number(this.delay) || 0, Math.ceil(Number(previousElapsed) || 0)),
      )
      this.timer = window.setTimeout(() => {
        this.timer = null
        this.tick()
      }, wait)
    },
    tick() {
      if (!this.running)
        return

      if (this.isDone) {
        this.stopStream()
        return
      }

      const start = this.content.length
      const nextChunk = markdownSource.slice(start, start + this.normalizedChunkSize)
      const tickStartedAt = typeof performance !== 'undefined' ? performance.now() : Date.now()
      this.content += nextChunk

      this.$nextTick(() => {
        const schedule = () => {
          if (!this.running)
            return
          const now = typeof performance !== 'undefined' ? performance.now() : Date.now()
          this.scheduleNextTick(now - tickStartedAt)
        }
        if (typeof window !== 'undefined' && typeof window.requestAnimationFrame === 'function')
          window.requestAnimationFrame(() => schedule())
        else
          schedule()
      })
    },
    startStream() {
      this.stopStream()
      this.running = true
      this.scheduleNextTick()
    },
    stopStream() {
      if (this.timer != null) {
        window.clearTimeout(this.timer)
        this.timer = null
      }
      this.running = false
    },
    toggleStream() {
      if (this.running)
        this.stopStream()
      else
        this.startStream()
    },
    restartStream() {
      if (!this.running)
        return
      this.startStream()
    },
    resetStream() {
      this.content = ''
      this.startStream()
    },
    fillAll() {
      this.content = markdownSource
      this.stopStream()
    },
  },
}
</script>

<template>
  <LineNumberHandoffCheck v-if="isLineNumberHandoffCheck" />

  <div v-else class="page">
    <header class="header">
      <div class="title">
        markstream-vue2 playground
      </div>
      <div class="sub">
        Vue CLI 4 demo: streaming markdown into the renderer with CDN workers
      </div>
    </header>

    <div class="layout">
      <section class="panel controls">
        <h2>Stream controls</h2>
        <div class="field">
          <label for="delay">Delay (ms)</label>
          <input id="delay" v-model.number="delay" type="number" min="4" max="200">
        </div>
        <div class="field">
          <label for="chunk">Chunk size</label>
          <input id="chunk" v-model.number="chunkSize" type="number" min="1" max="16">
        </div>
        <div class="actions">
          <button type="button" class="btn" @click="toggleStream">
            {{ running ? 'Pause' : 'Resume' }}
          </button>
          <button type="button" class="btn" @click="resetStream">
            Reset
          </button>
          <button type="button" class="btn ghost" @click="fillAll">
            Render all
          </button>
        </div>
        <div class="status">
          <div class="progress">
            <div class="bar" :style="{ width: `${progress}%` }" />
          </div>
          <div class="meta">
            {{ content.length }} / {{ totalLength }} ({{ progress }}%)
          </div>
        </div>
        <p class="note">
          This Webpack 4 playground uses CDN workers for KaTeX and Mermaid. D2 remains optional and falls back to source mode here.
        </p>
      </section>

      <section class="panel preview">
        <MarkdownRender
          :content="content"
          :final="isDone"
          :typewriter="false"
          :code-block-stream="true"
          code-block-dark-theme="vitesse-dark"
          code-block-light-theme="vitesse-dark"
          :code-block-props="codeBlockProps"
          :viewport-priority="false"
          :defer-nodes-until-visible="false"
          :batch-rendering="false"
          custom-id="vue2-demo"
          :custom-html-tags="customHtmlTags"
        />
      </section>
    </div>
  </div>
</template>

<style>
html,
body,
#app {
  margin: 0;
  min-height: 100%;
}

.page {
  min-height: 100vh;
  padding: 1.5rem 2rem 2.5rem;
  background: #f7f7fb;
  color: #111827;
  font-family: "IBM Plex Sans", "Segoe UI", sans-serif;
}

.header {
  display: flex;
  flex-direction: column;
  gap: 0.35rem;
  margin-bottom: 1.5rem;
}

.title {
  font-size: 1.6rem;
  font-weight: 700;
}

.sub {
  color: #4b5563;
}

.layout {
  display: grid;
  grid-template-columns: minmax(240px, 320px) minmax(0, 1fr);
  gap: 1.5rem;
  align-items: start;
}

.panel {
  background: #fff;
  border-radius: 12px;
  box-shadow: 0 12px 30px rgba(15, 23, 42, 0.08);
  padding: 1.25rem 1.5rem;
}

.controls h2 {
  margin: 0 0 1rem;
  font-size: 1.05rem;
}

.field {
  display: flex;
  flex-direction: column;
  gap: 0.35rem;
  margin-bottom: 0.9rem;
}

.field label {
  font-size: 0.9rem;
  color: #374151;
}

.field input {
  border: 1px solid #e5e7eb;
  border-radius: 8px;
  padding: 0.5rem 0.7rem;
  font-size: 0.95rem;
}

.actions {
  display: flex;
  gap: 0.5rem;
  flex-wrap: wrap;
  margin-top: 0.5rem;
}

.btn {
  border: none;
  background: #111827;
  color: #fff;
  padding: 0.45rem 0.9rem;
  border-radius: 8px;
  font-size: 0.9rem;
  cursor: pointer;
}

.btn.ghost {
  background: #e5e7eb;
  color: #111827;
}

.status {
  margin-top: 1rem;
}

.progress {
  width: 100%;
  height: 8px;
  background: #e5e7eb;
  border-radius: 999px;
  overflow: hidden;
}

.bar {
  height: 100%;
  background: linear-gradient(90deg, #3b82f6, #6366f1);
}

.meta {
  margin-top: 0.5rem;
  font-size: 0.85rem;
  color: #6b7280;
}

.note {
  margin-top: 0.9rem;
  font-size: 0.85rem;
  line-height: 1.5;
  color: #6b7280;
}

.preview {
  min-height: 70vh;
  overflow: auto;
}

@media (max-width: 960px) {
  .page {
    padding-left: 1rem;
    padding-right: 1rem;
  }

  .layout {
    grid-template-columns: 1fr;
  }
}
</style>

// playground-angular/src/app.component.ts
import type { OnDestroy, OnInit } from '@angular/core'
import { CommonModule } from '@angular/common'
import { ChangeDetectionStrategy, Component, computed, signal } from '@angular/core'
import { MarkstreamAngularComponent } from 'markstream-angular'
import { streamContent } from '../../playground/src/const/markdown'
import { LineNumberHandoffCheckComponent } from './line-number-handoff-check.component'
import { TestPageComponent } from './test-page.component'
import { TestSandboxComponent } from './test-sandbox.component'
import { ThinkingNodeComponent } from './thinking-node.component'

const markdownSource = typeof streamContent === 'string' ? streamContent : String(streamContent || '')
const THINKING_TAGS = ['thinking'] as const

function normalizePath(pathname: string | null | undefined) {
  const normalized = (pathname || '/').replace(/\/+$/, '')
  return normalized || '/'
}

function clampDelay(value: number) {
  if (!Number.isFinite(value))
    return 16
  return Math.min(200, Math.max(4, Math.round(value)))
}

function clampChunk(value: number) {
  if (!Number.isFinite(value))
    return 1
  return Math.min(16, Math.max(1, Math.floor(value)))
}

function readNumericInput(event: Event, fallback: number) {
  const value = Number((event.target as HTMLInputElement | null)?.value ?? fallback)
  return Number.isFinite(value) ? value : fallback
}

@Component({
  selector: 'playground-angular-root',
  standalone: true,
  imports: [CommonModule, MarkstreamAngularComponent, LineNumberHandoffCheckComponent, TestPageComponent, TestSandboxComponent],
  template: `
    <app-angular-test-sandbox *ngIf="isSandboxPage(); else nonSandbox" />

    <ng-template #nonSandbox>
      <app-line-number-handoff-check *ngIf="isLineNumberHandoffCheck(); else nonHandoff" />

      <ng-template #nonHandoff>
        <app-angular-test-page
          *ngIf="isTestPage(); else home"
          (navigateHome)="goHome()"
        />

        <ng-template #home>
          <div class="page">
          <header class="header">
            <div class="header-main">
              <div class="title">markstream-angular playground</div>
              <button type="button" class="btn" (click)="goToTest()">
                Open /test
              </button>
            </div>
            <div class="sub">
              Angular playground with streaming demo, standalone /test regression lab, and isolated /test-sandbox.
            </div>
          </header>

          <div class="layout">
            <section class="panel controls">
              <h2>Stream controls</h2>

              <div class="field">
                <label for="delay">Delay (ms)</label>
                <input
                  id="delay"
                  type="number"
                  min="4"
                  max="200"
                  [value]="delay()"
                  (input)="updateDelay($event)"
                >
              </div>

              <div class="field">
                <label for="chunk">Chunk size</label>
                <input
                  id="chunk"
                  type="number"
                  min="1"
                  max="16"
                  [value]="chunkSize()"
                  (input)="updateChunkSize($event)"
                >
              </div>

              <div class="actions">
                <button type="button" class="btn" (click)="toggleStream()">
                  {{ running() ? 'Pause' : 'Resume' }}
                </button>
                <button type="button" class="btn" (click)="resetStream()">
                  Reset
                </button>
                <button type="button" class="btn ghost" (click)="fillAll()">
                  Render all
                </button>
              </div>

              <div class="status">
                <div class="progress">
                  <div class="bar" [style.width.%]="progress()"></div>
                </div>
                <div class="meta">
                  {{ content().length }} / {{ totalLength }} ({{ progress() }}%)
                </div>
              </div>

              <p class="note">
                首页保留主 demo；更完整的跨框架回归入口在 <code>/test</code>，隔离版本对照在 <code>/test-sandbox</code>。
              </p>
            </section>

            <section class="panel preview">
              <markstream-angular
                [content]="content()"
                [final]="isDone()"
                [renderCodeBlocksAsPre]="false"
                [codeBlockStream]="true"
                [customHtmlTags]="thinkingTags"
                [customComponents]="customComponents"
              />
            </section>
          </div>
        </div>
        </ng-template>
      </ng-template>
    </ng-template>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent implements OnInit, OnDestroy {
  readonly thinkingTags = THINKING_TAGS
  readonly customComponents = {
    thinking: ThinkingNodeComponent,
  }

  readonly totalLength = markdownSource.length
  readonly currentPath = signal(typeof window === 'undefined' ? '/' : normalizePath(window.location.pathname))
  readonly content = signal('')
  readonly delay = signal(16)
  readonly chunkSize = signal(2)
  readonly running = signal(true)
  readonly normalizedChunkSize = computed(() => clampChunk(this.chunkSize()))
  readonly progress = computed(() => {
    if (!this.totalLength)
      return 0
    return Math.min(100, Math.round((this.content().length / this.totalLength) * 100))
  })

  readonly isDone = computed(() => this.content().length >= this.totalLength)
  readonly isTestPage = computed(() => this.currentPath() === '/test')
  readonly isSandboxPage = computed(() => this.currentPath() === '/test-sandbox')
  readonly isLineNumberHandoffCheck = computed(() => this.currentPath() === '/line-number-handoff-check')
  readonly isStandalonePage = computed(() => this.isTestPage() || this.isSandboxPage() || this.isLineNumberHandoffCheck())

  private timer: number | null = null

  ngOnInit() {
    if (typeof window !== 'undefined')
      window.addEventListener('popstate', this.handlePopState)
    if (!this.isStandalonePage())
      this.startStream()
  }

  ngOnDestroy() {
    if (typeof window !== 'undefined')
      window.removeEventListener('popstate', this.handlePopState)
    this.stopStream()
  }

  updateDelay(event: Event) {
    this.delay.set(clampDelay(readNumericInput(event, this.delay())))
    if (this.running() && !this.isStandalonePage())
      this.restartStream()
  }

  updateChunkSize(event: Event) {
    this.chunkSize.set(clampChunk(readNumericInput(event, this.chunkSize())))
  }

  goToTest() {
    this.navigate('/test')
  }

  goHome() {
    this.navigate('/')
  }

  toggleStream() {
    if (this.running())
      this.stopStream()
    else
      this.startStream()
  }

  resetStream() {
    this.content.set('')
    this.startStream()
  }

  fillAll() {
    this.content.set(markdownSource)
    this.stopStream()
  }

  private readonly handlePopState = () => {
    this.syncPath()
    if (this.isStandalonePage())
      this.stopStream()
    else if (!this.content())
      this.startStream()
  }

  private syncPath() {
    if (typeof window === 'undefined')
      return
    this.currentPath.set(normalizePath(window.location.pathname))
  }

  private navigate(pathname: string) {
    const nextPath = normalizePath(pathname)
    if (typeof window !== 'undefined' && nextPath !== normalizePath(window.location.pathname))
      window.history.pushState({}, '', nextPath)

    this.currentPath.set(nextPath)

    if (this.isStandalonePage())
      this.stopStream()
    else if (!this.content() || this.content().length >= markdownSource.length)
      this.resetStream()
  }

  private tick() {
    if (this.isDone()) {
      this.stopStream()
      return
    }

    this.content.update((current) => {
      const nextChunk = markdownSource.slice(current.length, current.length + this.normalizedChunkSize())
      return current + nextChunk
    })
  }

  private startStream() {
    this.stopStream()
    if (typeof window === 'undefined')
      return
    this.running.set(true)
    this.timer = window.setInterval(() => this.tick(), this.delay())
  }

  private stopStream() {
    if (this.timer != null && typeof window !== 'undefined') {
      window.clearInterval(this.timer)
      this.timer = null
    }
    this.running.set(false)
  }

  private restartStream() {
    if (!this.running())
      return
    this.startStream()
  }
}
